language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"

#cpanm --quiet --installdeps --notest .

addons:
  postgresql: "9.3"
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
