language: perl
perl:
  - "5.18"

addons:
  postgresql: "9.3"
  
before_install:
  #- sudo apt-get install apache2
  - sudo apt-get install libpq-dev
  - sudo apt-get install r-base-core
  - psql -c 'CREATE DATABASE polydb;' -U postgres
  - cpanm --quiet --installdeps --notest Parse::PlainConfig
  - cpanm --quiet --installdeps --notest Config::Validate
  - cpanm --quiet --installdeps --notest File::System
  - cpanm --quiet --installdeps --notest DBD::Pg
  - cpanm --quiet --installdeps --notest Template
  - cpanm --quiet --installdeps --notest Algorithm::Combinatorics
  - cpanm --quiet --installdeps --notest Log::Log4perl
  - cpanm --quiet --installdeps --notest Term::ProgressBar
