language: perl
perl:
  - "5.18"

addons:
  postgresql: "9.3"
  
before_install:
  - sudo apt-get install libpq-dev
  - sudo apt-get install r-base-core
  - psql -c 'CREATE DATABASE polydb;' -U postgres
  - cpanm --quiet --installdeps --notest Parse::PlainConfig
  
