language: perl
perl:
  - "5.20"

addons:
  postgresql: "9.3"
  
# Use this to prepare the system to install prerequisites or dependencies.
before_install:
  - sudo apt-get update
  - sudo apt-get autoremove
  - sudo apt-get install -y --force-yes apache2
  - sudo apt-get install libpq-dev
  - sudo apt-get install r-base-core
  - sudo apt-get install libdb4.8-dev
  - psqlh -c 'CREATE DATABASE polydb;' -U postgres
# Use this to install any prerequisites or dependencies necessary to run your build.
install:
  - cpanm Config::Validate
  - cpanm File::System
  - cpanm DBD::Pg
  - cpanm Template
  - cpanm Algorithm::Combinatorics
  - cpanm Log::Log4perl
  - cpanm Term::ProgressBar
  - svn export http://svn.code.sf.net/p/vcftools/code/ vcftools
  - cpanm CGI::Session::File
  - cpanm --notest Paranoid
  - cpanm Parse::PlainConfig
  - cpanm IPC::Run
  - cpanm URI::Escape
  - cpanm DB_File
  - cpanm Text::Markdown
  - cpanm File::Slurp

# Use this to prepare your build for testing
# e.g. copy database configurations, environment variables, etc.
before_script: true

# Default is specific to project language
# All commands must exit with code 0 on success. 
# Anything else is considered failure.
script:
  - ./polydb_installer.pl --config .travis-ci.configuration_file.conf  --skip_warning

after_success: true

after_failure: true

after_script: true

