set vcf_list=vcf_list.pol_sites


# This script tries to detect two issues frequently found in VCFs generated by GATK

# - Two calls on the same positon where the alternative field is equal '.' on both calls, indicating the sample is equal to reference. In some cases the reference sequence is reported differently in each calls (example 1,2 and 4), in others the reference sequence is exactly the same (example 3 below)   


# Example 1
# 7000000184540662        24681   .       G       .       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       GT      .       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97

# Example 2
# 7000000184540662        24681   .       C       .       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       G       .       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97

# Example 3
# 7000000184540662        499612  .       C       .       2297.85 PASS    AC=0;AF=0.00;AN=2;DP=80;MQ=49.65;MQ0=0  GT:DP   0/0:80
# 7000000184540662        499612  .       C       .       2452.27 PASS    AC=0;AF=0.00;AN=2;DP=82;MQ=50.08;MQ0=0  GT:DP   0/0:82

# Example 4
# 7000000184540662        24681   .       CT       .       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       GT       .       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97


awk '{print $2}' FS="\t" $vcf_list > $vcf_list.only_path
foreach file ( `cat  $vcf_list.only_path` )
set double_calls=`awk ' $1 == last_chrom && $2 == last_position && $5 == "." && last_alt_genotype == "." {print last_line; print $0}{last_chrom = $1; last_position = $2; last_line = $0; last_alt_genotype = $5}' \
$file FS="\t" | tee $file.double_calls | wc -l`
echo $file " number of double calls:" $double_calls
end


# - Polymorphism of the same kind (substitution, insertion or deletion) reported in the same position.

# Example 1 (substitution)
# 7000000184540662        24681   .       C       G       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       C       .       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97

# Example 2 (insertion)
# 7000000184540662        24681   .       C       CG       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       C       CT       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97

# Example 3 (deletion)
# 7000000184540662        24681   .       CG       C       2833.68 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97
# 7000000184540662        24681   .       CC       C       3830.50 PASS    AC=0;AF=0.00;AN=2;DP=97;MQ=34.74;MQ0=0  GT:DP   0/0:97



set sample = 0
foreach file ( `cat  $vcf_list.only_path` )
echo "Sample $sample ..."
set double_calls=`awk ' $1 == last_chrom && $2 == last_position && length($5) == length(last_alt_genotype) && length($4) == length(last_ref_genotype) && (last_ref_genotype != $4 || last_alt_genotype != $5 ) {print last_line; print $0}{last_chrom = $1; last_position = $2; last_line = $0; last_alt_genotype = $5; last_ref_genotype = $4}' \
$file FS="\t" | tee s$sample.double_different | wc -l`
echo "\tNumber of double different calls: $double_calls"
echo "\tList of errors saved on: s$sample.double_different"
@ sample++
end



